"""
ET AI Concierge — Compliance Wrapper
Wraps every agent response with SEBI disclaimers, audit logging, and HITL checks.
"""
from datetime import datetime
from typing import Optional
from state import AgentResponse, UserProfile
from database import log_audit


SEBI_DISCLAIMER = (
    "This recommendation is generated by AI and is for informational purposes only. "
    "It does not constitute registered investment advice under SEBI IA Regulations 2024. "
    "Please consult a SEBI-registered advisor before investing."
)

HIGH_STAKES_TYPES = ["LOAN_APPLICATION", "INSURANCE_CLAIM", "LARGE_TRANSFER"]


class ComplianceWrapper:
    """Pass every agent response through compliance checks before delivery."""

    def wrap(
        self,
        agent_response: AgentResponse,
        user: UserProfile,
        session_id: str,
        intent: str = "",
    ) -> AgentResponse:

        # 1. SEBI: Disclose AI usage on investment recommendations
        if agent_response.contains_investment_advice:
            agent_response.append_disclaimer(SEBI_DISCLAIMER)

        # 2. Audit log every recommendation
        log_audit(
            user_id=user.id,
            session_id=session_id,
            agent_id=agent_response.agent_id,
            intent=intent,
            recommendation={"content": agent_response.content, "type": agent_response.type},
            sources=agent_response.sources,
            reasoning_trace=agent_response.reasoning_trace or "",
            model_version="llama-3.3-70b-versatile",
            confidence=agent_response.confidence_score,
            hitl_triggered=self.requires_human_oversight(agent_response),
            disclaimer_shown=agent_response.contains_investment_advice,
        )

        # 3. HITL escalation check
        if self.requires_human_oversight(agent_response):
            return self.escalate_to_human(agent_response, user)

        return agent_response

    def requires_human_oversight(self, response: AgentResponse) -> bool:
        return response.type in HIGH_STAKES_TYPES or response.confidence_score < 0.7

    def escalate_to_human(self, response: AgentResponse, user: UserProfile) -> AgentResponse:
        response.content += (
            "\n\n🔄 **This request requires specialist review.** "
            "I'm connecting you with a human advisor who can assist directly. "
            "Estimated wait: < 2 minutes."
        )
        response.type = "HITL_ESCALATION"
        return response


compliance_wrapper = ComplianceWrapper()
